@startuml  overview

title How I suspect the Aer Lingus booking system was implemented
actor User 
autoactivate on
User -> Website: Make booking 
group "transaction"
Website -> Backend: Process booking
database Database
participant "Payment\nProvider" as Provider 
Backend -> Provider: Bill the card 
return success
note left: website dies at this point
destroy Website
end
Backend -> Database: Write booking \n(no check for duplicates) 
return yolo
par 
Backend -> Website !! : Attempt to reply
Backend -> EmailServer: Confirm booking
EmailServer --> User: Send confirmation email 
Website --> User: Internal server error
end

@enduml