@startuml overview

title How a booking system should work
autoactivate on
actor User 
User -> Website: Make booking 
entity   EmailServer
Website -> Backend: Process booking
database Database
Backend -> Database: Write booking (check for duplicates)
entity "Payment\nProvider" as Provider 
Backend -> Provider: Bill the card 
return success
Backend -> Database: Flag transaction complete
par 
Backend -> Website: LGTM
Backend -> EmailServer: Send confirmation
EmailServer -> User: Send email
end
Website -> User: LGTM
activate Sentinel
Sentinel -> Database: Checking for \nlost/duplicate transactions, etc
Sentinel -> EmailServer : Verifying emails successfully handed off 

Backend -> LogAggregator: application crash reports
@enduml