@startuml overview

title Phoenix/Plug browser sessions 
actor Browser 
autoactivate on
== Session creation ==
' activate Browser
Browser -> Website: request page
Website -> Website: encrypt/sign \nsession data into cookie
Website --> Browser: return page and cookie
Browser -> Browser: manage cookie expiration
' deactivate Browser
== User inactive ==
Browser -> Browser !! : inactive

== User active ==
' activate Browser
Browser -> Website: request page \n (session in cookie)
Website -> Website: decode session 
Website -> Browser: return page and updated session
@enduml